#!/usr/bin/env python
"""Rolling backtest for Dixon–Coles models (league-by-league).

What this script does
---------------------
1) Ingests historical match data from the same sources as train_models.py
2) Chooses an evaluation set per league (default: the most recent season)
3) Runs a *rolling* evaluation with periodic retraining (no leakage)
4) Computes probabilistic metrics (log loss, Brier), plus accuracy
5) Optionally compares against bookmaker implied probabilities (if odds exist)
6) Optionally grid-searches over (half-life, xg_weight, draw_threshold)
7) Stores best model parameters by log loss and best expected-goals threshold by exp_accuracy

Outputs
-------
- One per-match prediction CSV per (league, param combo)
- One summary CSV across all tested combos
- One "best params" JSON per league (lowest model log loss)
- One "best exp threshold" JSON per league (highest exp_accuracy)

Examples
--------

Backtest a single league on its most recent season, tuning half-life and xG weight:

  python backtest_models.py `
    --all-euro-dir /data/euro_excels `
    --new-leagues-file /data/new_leagues_data.xlsx `
    --league-id E0 `
    --out-dir backtests `
    --last-n-seasons 3 `
    --half-life-days-grid 0,90,180,365 `
    --xg-weight-grid 0,0.25,0.5 `
    --draw-threshold-grid 0.10,0.15,0.20,0.25,0.30,0.35 `
    --retrain-every 50

Backtest all leagues and keep parameters fixed:

  python backtest_models.py `
    --all-euro-dir /data/euro_excels `
    --new-leagues-file /data/new_leagues_data.xlsx `
    --out-dir backtests `
    --half-life-days-grid 180 `
    --xg-weight-grid 0 `
    --draw-threshold-grid 0.25

Author: generated by ChatGPT
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import asdict
from math import log
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np
import pandas as pd

from src.dixon_coles import DixonColesModel
from src.ingest import build_master_dataset


EPS = 1e-15


def _expected_goal_outcome(exp_home_goals: float, exp_away_goals: float, draw_threshold: float) -> str:
    diff = float(exp_home_goals) - float(exp_away_goals)
    if abs(diff) <= float(draw_threshold):
        return "D"
    return "H" if diff > 0 else "A"


def _season_start_year(season: str) -> Optional[int]:
    if season is None or (isinstance(season, float) and np.isnan(season)):
        return None
    m = re.search(r"(\d{4})", str(season))
    return int(m.group(1)) if m else None


def _parse_float_grid(s: str) -> List[float]:
    """Parse comma-separated floats (e.g. '0,90,180')."""
    if s is None:
        return []
    parts = [p.strip() for p in str(s).split(",") if p.strip() != ""]
    return [float(p) for p in parts]


def _discover_all_euro_files(all_euro_dir: Optional[str]) -> List[Path]:
    if not all_euro_dir:
        return []
    d = Path(all_euro_dir)
    if not d.exists():
        raise FileNotFoundError(f"all-euro-dir not found: {d}")

    files = sorted(d.glob("all-euro-data-*.xlsx"))
    if not files:
        files = sorted(d.glob("*.xlsx"))
    return list(files)


def _true_outcome(home_goals: float, away_goals: float) -> str:
    if home_goals > away_goals:
        return "H"
    if home_goals < away_goals:
        return "A"
    return "D"


def _multiclass_brier(p: np.ndarray, y: np.ndarray) -> float:
    """Multi-class Brier score for one observation.

    p: shape (3,) probabilities in H,D,A order
    y: shape (3,) one-hot
    """
    return float(np.sum((p - y) ** 2))


def _odds_to_probs(odds_h: float, odds_d: float, odds_a: float) -> Optional[Tuple[float, float, float]]:
    """Convert 1X2 odds to implied probabilities and remove overround."""
    try:
        if not (np.isfinite(odds_h) and np.isfinite(odds_d) and np.isfinite(odds_a)):
            return None
        if odds_h <= 1e-9 or odds_d <= 1e-9 or odds_a <= 1e-9:
            return None
        inv = np.array([1.0 / odds_h, 1.0 / odds_d, 1.0 / odds_a], dtype=float)
        s = float(inv.sum())
        if s <= 0:
            return None
        p = inv / s
        return float(p[0]), float(p[1]), float(p[2])
    except Exception:
        return None


def _calibration_table(df: pd.DataFrame, prob_col: str, correct_col: str, n_bins: int = 10) -> pd.DataFrame:
    """Calibration of a scalar probability vs empirical accuracy.

    We bin `prob_col` into n_bins equal-width bins on [0,1] and compute:
      - count
      - mean_pred_prob
      - empirical_accuracy
    """
    x = df[[prob_col, correct_col]].dropna().copy()
    if x.empty:
        return pd.DataFrame(columns=["bin", "count", "mean_pred_prob", "empirical_accuracy"]) 

    x["bin"] = pd.cut(x[prob_col], bins=np.linspace(0, 1, n_bins + 1), include_lowest=True)
    out = (
        x.groupby("bin", observed=False)
        .agg(
            count=(prob_col, "size"),
            mean_pred_prob=(prob_col, "mean"),
            empirical_accuracy=(correct_col, "mean"),
        )
        .reset_index()
    )
    return out


def _select_eval_matches(
    played: pd.DataFrame,
    eval_season: Optional[str] = None,
    eval_start_date: Optional[str] = None,
) -> Tuple[pd.DataFrame, str]:
    """Choose evaluation matches.

    Priority:
      1) eval_start_date (YYYY-MM-DD)
      2) eval_season
      3) most recent season in data
    """
    if eval_start_date:
        start = pd.to_datetime(eval_start_date, errors="coerce")
        if pd.isna(start):
            raise ValueError(f"Could not parse eval_start_date: {eval_start_date!r}")
        ev = played[played["datetime"] >= start].copy()
        label = f"from_{start.date().isoformat()}"
        return ev, label

    if eval_season:
        ev = played[played["season"].astype(str) == str(eval_season)].copy()
        label = f"season_{eval_season}"
        return ev, label

    # most recent season by extracted start-year
    seasons = played["season"].dropna().astype(str).unique().tolist()
    if not seasons:
        return played.iloc[0:0].copy(), "no_season"
    seasons_sorted = sorted(seasons, key=lambda s: (_season_start_year(s) or -10**9, s))
    last = seasons_sorted[-1]
    ev = played[played["season"].astype(str) == str(last)].copy()
    label = f"season_{last}"
    return ev, label


def rolling_backtest(
    played: pd.DataFrame,
    *,
    half_life_days: float,
    xg_weight: float,
    draw_threshold: float,
    max_goals: int,
    l2: float,
    retrain_every: int,
    min_train_matches: int,
    eval_season: Optional[str],
    eval_start_date: Optional[str],
) -> Tuple[pd.DataFrame, Dict]:
    """Run a rolling backtest on a single league dataframe."""

    played = played.sort_values("datetime").reset_index(drop=True)

    eval_df, eval_label = _select_eval_matches(played, eval_season=eval_season, eval_start_date=eval_start_date)
    eval_df = eval_df.sort_values("datetime").reset_index(drop=True)
    if eval_df.empty:
        return eval_df, {
            "eval_label": eval_label,
            "n_eval": 0,
            "n_pred": 0,
            "error": "empty evaluation set",
        }

    # Decay rate
    if half_life_days and half_life_days > 0:
        xi = log(2.0) / float(half_life_days)
    else:
        xi = 0.0

    preds: List[Dict] = []

    # Rolling: retrain at chunk boundaries based on eval index
    n_eval = len(eval_df)
    for start in range(0, n_eval, max(1, retrain_every)):
        chunk = eval_df.iloc[start : start + max(1, retrain_every)].copy()
        as_of = pd.to_datetime(chunk["datetime"].iloc[0])

        train = played[played["datetime"] < as_of].copy()
        if len(train) < min_train_matches:
            # Not enough history yet; skip these matches
            for _, r in chunk.iterrows():
                preds.append(
                    {
                        "datetime": r["datetime"],
                        "season": r.get("season"),
                        "home_team": r["home_team"],
                        "away_team": r["away_team"],
                        "home_goals": r["home_goals"],
                        "away_goals": r["away_goals"],
                        "true_outcome": _true_outcome(r["home_goals"], r["away_goals"]),
                        "exp_home_goals": np.nan,
                        "exp_away_goals": np.nan,
                        "exp_outcome": np.nan,
                        "exp_correct": np.nan,
                        "p_home": np.nan,
                        "p_draw": np.nan,
                        "p_away": np.nan,
                        "pred_outcome": np.nan,
                        "top_prob": np.nan,
                        "model_logloss": np.nan,
                        "model_brier": np.nan,
                        "model_correct": np.nan,
                        "book_p_home": np.nan,
                        "book_p_draw": np.nan,
                        "book_p_away": np.nan,
                        "book_logloss": np.nan,
                        "book_brier": np.nan,
                        "book_correct": np.nan,
                        "note": f"skipped_not_enough_train({len(train)}<{min_train_matches})",
                    }
                )
            continue

        model = DixonColesModel(xi=xi, max_goals=max_goals, l2=l2, xg_weight=float(xg_weight))

        try:
            model.fit(train)
        except Exception as e:
            # If fit fails, mark predictions as missing for this chunk
            for _, r in chunk.iterrows():
                preds.append(
                    {
                        "datetime": r["datetime"],
                        "season": r.get("season"),
                        "home_team": r["home_team"],
                        "away_team": r["away_team"],
                        "home_goals": r["home_goals"],
                        "away_goals": r["away_goals"],
                        "true_outcome": _true_outcome(r["home_goals"], r["away_goals"]),
                        "exp_home_goals": np.nan,
                        "exp_away_goals": np.nan,
                        "exp_outcome": np.nan,
                        "exp_correct": np.nan,
                        "p_home": np.nan,
                        "p_draw": np.nan,
                        "p_away": np.nan,
                        "pred_outcome": np.nan,
                        "top_prob": np.nan,
                        "model_logloss": np.nan,
                        "model_brier": np.nan,
                        "model_correct": np.nan,
                        "book_p_home": np.nan,
                        "book_p_draw": np.nan,
                        "book_p_away": np.nan,
                        "book_logloss": np.nan,
                        "book_brier": np.nan,
                        "book_correct": np.nan,
                        "note": f"fit_failed: {e}",
                    }
                )
            continue

        for _, r in chunk.iterrows():
            ht = r["home_team"]
            at = r["away_team"]
            hg = float(r["home_goals"])
            ag = float(r["away_goals"])
            true = _true_outcome(hg, ag)

            # bookmaker probs (if odds exist)
            odds_h = r.get("odds_home", np.nan)
            odds_d = r.get("odds_draw", np.nan)
            odds_a = r.get("odds_away", np.nan)
            book = _odds_to_probs(odds_h, odds_d, odds_a)

            try:
                lam, nu = model.expected_goals(ht, at)
                exp_out = _expected_goal_outcome(lam, nu, draw_threshold)
                probs = model.outcome_probs(ht, at)
                p = np.array([probs["H"], probs["D"], probs["A"]], dtype=float)
                p = np.clip(p, EPS, 1.0)
                p = p / p.sum()

                pred_idx = int(np.argmax(p))
                pred_out = ["H", "D", "A"][pred_idx]
                top_prob = float(np.max(p))

                y = np.array([1.0 if true == "H" else 0.0, 1.0 if true == "D" else 0.0, 1.0 if true == "A" else 0.0])
                model_logloss = -float(np.log(p[["H", "D", "A"].index(true)]))
                model_brier = _multiclass_brier(p, y)
                model_correct = float(pred_out == true)
                exp_correct = float(exp_out == true)

            except KeyError as e:
                lam, nu = np.nan, np.nan
                exp_out = np.nan
                p = np.array([np.nan, np.nan, np.nan], dtype=float)
                pred_out = np.nan
                top_prob = np.nan
                model_logloss = np.nan
                model_brier = np.nan
                model_correct = np.nan
                exp_correct = np.nan
                note = f"unknown_team: {e}"
            except Exception as e:
                lam, nu = np.nan, np.nan
                exp_out = np.nan
                p = np.array([np.nan, np.nan, np.nan], dtype=float)
                pred_out = np.nan
                top_prob = np.nan
                model_logloss = np.nan
                model_brier = np.nan
                model_correct = np.nan
                exp_correct = np.nan
                note = f"pred_failed: {e}"
            else:
                note = ""

            # Bookmaker metrics
            if book is not None:
                bp = np.array(book, dtype=float)
                bp = np.clip(bp, EPS, 1.0)
                bp = bp / bp.sum()
                bpred_out = ["H", "D", "A"][int(np.argmax(bp))]
                by = np.array([1.0 if true == "H" else 0.0, 1.0 if true == "D" else 0.0, 1.0 if true == "A" else 0.0])
                blogloss = -float(np.log(bp[["H", "D", "A"].index(true)]))
                bbrier = _multiclass_brier(bp, by)
                bcorrect = float(bpred_out == true)
                book_ph, book_pd, book_pa = float(bp[0]), float(bp[1]), float(bp[2])
            else:
                book_ph = book_pd = book_pa = np.nan
                blogloss = bbrier = bcorrect = np.nan

            preds.append(
                {
                    "datetime": r["datetime"],
                    "season": r.get("season"),
                    "home_team": ht,
                    "away_team": at,
                    "home_goals": hg,
                    "away_goals": ag,
                    "true_outcome": true,
                    "exp_home_goals": lam,
                    "exp_away_goals": nu,
                    "exp_outcome": exp_out,
                    "exp_correct": exp_correct,
                    "p_home": float(p[0]) if np.isfinite(p[0]) else np.nan,
                    "p_draw": float(p[1]) if np.isfinite(p[1]) else np.nan,
                    "p_away": float(p[2]) if np.isfinite(p[2]) else np.nan,
                    "pred_outcome": pred_out,
                    "top_prob": top_prob,
                    "model_logloss": model_logloss,
                    "model_brier": model_brier,
                    "model_correct": model_correct,
                    "book_p_home": book_ph,
                    "book_p_draw": book_pd,
                    "book_p_away": book_pa,
                    "book_logloss": blogloss,
                    "book_brier": bbrier,
                    "book_correct": bcorrect,
                    "note": note,
                }
            )

    pred_df = pd.DataFrame(preds)
    n_pred = int(pred_df["model_logloss"].notna().sum())

    # Summary metrics (model)
    model_mask = pred_df["model_logloss"].notna()
    if model_mask.any():
        model_logloss = float(pred_df.loc[model_mask, "model_logloss"].mean())
        model_brier = float(pred_df.loc[model_mask, "model_brier"].mean())
        model_acc = float(pred_df.loc[model_mask, "model_correct"].mean())
        exp_acc = float(pred_df.loc[model_mask, "exp_correct"].mean())
    else:
        model_logloss = model_brier = model_acc = exp_acc = float("nan")

    # Summary metrics (bookmaker)
    book_mask = pred_df["book_logloss"].notna()
    if book_mask.any():
        book_logloss = float(pred_df.loc[book_mask, "book_logloss"].mean())
        book_brier = float(pred_df.loc[book_mask, "book_brier"].mean())
        book_acc = float(pred_df.loc[book_mask, "book_correct"].mean())
    else:
        book_logloss = book_brier = book_acc = float("nan")

    summary = {
        "eval_label": eval_label,
        "n_eval": int(len(eval_df)),
        "n_pred": n_pred,
        "half_life_days": float(half_life_days),
        "xi": float(xi),
        "xg_weight": float(xg_weight),
        "draw_threshold": float(draw_threshold),
        "max_goals": int(max_goals),
        "l2": float(l2),
        "retrain_every": int(retrain_every),
        "min_train_matches": int(min_train_matches),
        "model_logloss": model_logloss,
        "model_brier": model_brier,
        "model_accuracy": model_acc,
        "exp_accuracy": exp_acc,
        "book_logloss": book_logloss,
        "book_brier": book_brier,
        "book_accuracy": book_acc,
    }
    return pred_df, summary


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Rolling backtest Dixon–Coles models")

    p.add_argument("--all-euro-dir", type=str, default=None, help="Directory of all-euro-data-*.xlsx (optional)")
    p.add_argument(
        "--all-euro-files",
        type=str,
        nargs="*",
        default=None,
        help="Explicit list of all-euro-data workbooks (optional; overrides --all-euro-dir)",
    )
    p.add_argument("--new-leagues-file", type=str, default=None, help="Path to new_leagues_data.xlsx (optional)")

    p.add_argument("--out-dir", type=str, required=True, help="Directory to write backtest outputs")
    p.add_argument("--processed-out", type=str, default=None, help="Optional path to save unified dataset (csv/parquet)")

    p.add_argument("--league-id", type=str, default=None, help="Backtest only this league_id (e.g., E0). Default: all")
    p.add_argument("--last-n-seasons", type=int, default=3, help="Keep last N seasons per league during ingestion")

    p.add_argument(
        "--eval-season",
        type=str,
        default=None,
        help="Season string to evaluate on (e.g., 2025/2026). Default: most recent season per league",
    )
    p.add_argument(
        "--eval-start-date",
        type=str,
        default=None,
        help="Evaluate matches from this date (YYYY-MM-DD). Overrides --eval-season.",
    )

    p.add_argument(
        "--half-life-days-grid",
        type=str,
        default="180",
        help="Comma-separated half-life grid in days. Use 0 to disable decay. Example: 0,90,180,365",
    )
    p.add_argument(
        "--xg-weight-grid",
        type=str,
        default="0",
        help="Comma-separated xg_weight grid (0..1). Example: 0,0.25,0.5",
    )
    p.add_argument(
        "--draw-threshold-grid",
        type=str,
        default=None,
        help="Comma-separated draw-threshold grid for exp_outcome. Example: 0.10,0.15,0.20,0.25,0.30,0.35",
    )
    p.add_argument("--max-goals", type=int, default=10, help="Score grid truncation")
    p.add_argument("--l2", type=float, default=0.0, help="Ridge penalty")
    p.add_argument(
        "--draw-threshold",
        type=float,
        default=0.25,
        help="If abs(exp_home_goals - exp_away_goals) is at or below this cutoff, set exp_outcome to 'D'.",
    )
    p.add_argument("--retrain-every", type=int, default=50, help="Retrain every N eval matches")
    p.add_argument("--min-train-matches", type=int, default=80, help="Minimum matches required to fit at each retrain")
    p.add_argument("--calibration-bins", type=int, default=10, help="Bins for top-prob calibration output")

    return p.parse_args()


def _save_dataframe(df: pd.DataFrame, out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    suf = out_path.suffix.lower()
    if suf in [".parquet", ".pq"]:
        try:
            df.to_parquet(out_path, index=False)
        except Exception as e:
            fallback = out_path.with_suffix(".csv")
            df.to_csv(fallback, index=False)
            print(f"[warn] Failed to write parquet ({e}). Wrote CSV instead: {fallback}")
    else:
        df.to_csv(out_path, index=False)


def main() -> None:
    args = parse_args()

    # Resolve inputs
    if args.all_euro_files:
        all_euro_paths = [Path(p) for p in args.all_euro_files]
    else:
        all_euro_paths = _discover_all_euro_files(args.all_euro_dir)
    new_leagues_path = Path(args.new_leagues_file) if args.new_leagues_file else None

    if not all_euro_paths and new_leagues_path is None:
        raise SystemExit("No inputs provided. Use --all-euro-dir/--all-euro-files and/or --new-leagues-file")

    master = build_master_dataset(
        all_euro_paths=all_euro_paths,
        new_leagues_path=new_leagues_path,
        last_n_seasons=args.last_n_seasons,
    )
    if master.empty:
        raise SystemExit("Master dataset is empty after ingestion.")

    if args.processed_out:
        _save_dataframe(master, Path(args.processed_out))

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    half_life_grid = _parse_float_grid(args.half_life_days_grid)
    xg_grid = _parse_float_grid(args.xg_weight_grid)
    draw_threshold_grid = _parse_float_grid(args.draw_threshold_grid)
    if not half_life_grid:
        half_life_grid = [180.0]
    if not xg_grid:
        xg_grid = [0.0]
    if not draw_threshold_grid:
        draw_threshold_grid = [float(args.draw_threshold)]

    # Filter leagues
    if args.league_id:
        leagues = [str(args.league_id)]
    else:
        leagues = sorted(master["league_id"].dropna().astype(str).unique().tolist())

    summaries: List[Dict] = []
    best_params: Dict[str, Dict] = {}
    best_exp_thresholds: Dict[str, Dict] = {}

    for league_id in leagues:
        g = master[master["league_id"].astype(str) == str(league_id)].copy()
        g = g.dropna(subset=["datetime", "home_team", "away_team", "home_goals", "away_goals"]).copy()
        if g.empty:
            print(f"[warn] {league_id}: no played matches with datetime")
            continue

        league_dir = out_dir / str(league_id)
        league_dir.mkdir(parents=True, exist_ok=True)

        # Keep deterministic ordering
        g = g.sort_values("datetime").reset_index(drop=True)

        best = None
        best_exp = None
        for half_life in half_life_grid:
            for xg_w in xg_grid:
                for draw_threshold in draw_threshold_grid:
                    pred_df, summary = rolling_backtest(
                        g,
                        half_life_days=half_life,
                        xg_weight=xg_w,
                        draw_threshold=draw_threshold,
                        max_goals=args.max_goals,
                        l2=args.l2,
                        retrain_every=args.retrain_every,
                        min_train_matches=args.min_train_matches,
                        eval_season=args.eval_season,
                        eval_start_date=args.eval_start_date,
                    )
                    summary["league_id"] = str(league_id)
                    summaries.append(summary)

                    tag = f"hl{half_life:g}_xg{xg_w:g}_dt{draw_threshold:g}".replace(".", "p")
                    pred_path = league_dir / f"{tag}_predictions.csv"
                    pred_df.to_csv(pred_path, index=False)

                    # Calibration on top_prob
                    cal_df = pred_df.copy()
                    cal_df["model_correct"] = pd.to_numeric(cal_df["model_correct"], errors="coerce")
                    cal = _calibration_table(cal_df, prob_col="top_prob", correct_col="model_correct", n_bins=args.calibration_bins)
                    cal.to_csv(league_dir / f"{tag}_calibration.csv", index=False)

                    # Track best by model_logloss (lower is better)
                    ll = summary.get("model_logloss")
                    if ll is not None and np.isfinite(ll):
                        if best is None or float(ll) < float(best["model_logloss"]):
                            best = dict(summary)

                    # Track best expected-goals threshold by exp_accuracy (higher is better).
                    ea = summary.get("exp_accuracy")
                    if ea is not None and np.isfinite(ea):
                        if best_exp is None:
                            best_exp = dict(summary)
                        else:
                            better_acc = float(ea) > float(best_exp["exp_accuracy"])
                            tie_better_ll = float(ea) == float(best_exp["exp_accuracy"]) and float(summary.get("model_logloss", np.inf)) < float(best_exp.get("model_logloss", np.inf))
                            tie_smaller_threshold = float(ea) == float(best_exp["exp_accuracy"]) and float(summary.get("model_logloss", np.inf)) == float(best_exp.get("model_logloss", np.inf)) and float(draw_threshold) < float(best_exp.get("draw_threshold", np.inf))
                            if better_acc or tie_better_ll or tie_smaller_threshold:
                                best_exp = dict(summary)

                    print(
                        f"[ok] {league_id} {tag}: n_pred={summary.get('n_pred')}, "
                        f"model_logloss={summary.get('model_logloss')}, exp_accuracy={summary.get('exp_accuracy')}, "
                        f"book_logloss={summary.get('book_logloss')}"
                    )

        if best is not None:
            best_params[str(league_id)] = best
            (league_dir / "best_params.json").write_text(json.dumps(best, indent=2), encoding="utf-8")
        if best_exp is not None:
            best_exp_thresholds[str(league_id)] = best_exp
            (league_dir / "best_exp_threshold.json").write_text(json.dumps(best_exp, indent=2), encoding="utf-8")

    # Write overall summaries
    summary_df = pd.DataFrame(summaries)
    summary_df.to_csv(out_dir / "summary.csv", index=False)
    (out_dir / "summary.json").write_text(json.dumps(summaries, indent=2), encoding="utf-8")
    (out_dir / "best_params_all.json").write_text(json.dumps(best_params, indent=2), encoding="utf-8")
    (out_dir / "best_exp_thresholds_all.json").write_text(json.dumps(best_exp_thresholds, indent=2), encoding="utf-8")


if __name__ == "__main__":
    main()
