#!/usr/bin/env python
"""Batch or single-match predictions from a saved Dixon–Coles artifact.

Example:
  python predict_matches.py `
    --artifact models/E0.joblib `
    --fixtures fixtures.csv `
    --home-col HomeTeam `
    --away-col AwayTeam `
    --out predictions.csv

The fixtures file can be CSV or Excel.

Author: generated by ChatGPT
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, Tuple

import joblib
import numpy as np
import pandas as pd

from src.dixon_coles import model_from_artifact


def expected_goal_outcome(exp_home_goals: float, exp_away_goals: float, draw_threshold: float) -> str:
    diff = float(exp_home_goals) - float(exp_away_goals)
    if abs(diff) <= float(draw_threshold):
        return "D"
    return "H" if diff > 0 else "A"


def load_threshold_map(path: str | None) -> Dict[str, float]:
    if not path:
        return {}
    raw = json.loads(Path(path).read_text(encoding="utf-8"))
    out: Dict[str, float] = {}
    for league_id, payload in raw.items():
        if isinstance(payload, dict) and "draw_threshold" in payload:
            out[str(league_id)] = float(payload["draw_threshold"])
    return out


def resolve_draw_threshold(league_id: str, default_threshold: float, threshold_map: Dict[str, float]) -> float:
    return float(threshold_map.get(str(league_id), default_threshold))


def load_artifact_model(artifact_path: Path) -> Tuple[dict, object]:
    artifact = joblib.load(artifact_path)
    model = model_from_artifact(artifact)
    return artifact, model


def predict_row(
    *,
    model,
    league_id: str,
    home_team: str,
    away_team: str,
    top_k_scores: int,
    on_unknown_team: str,
    draw_threshold: float,
) -> Dict:
    try:
        lam_raw, nu_raw = model.expected_goals(home_team, away_team)
        probs = model.outcome_probs(home_team, away_team)
        lam = round(lam_raw, 2)
        nu = round(nu_raw, 2)
        ph = round(probs["H"], 3)
        pd_raw = round(probs["D"], 3)
        pa = round(probs["A"], 3)

        matrix = model.score_matrix(home_team, away_team)
        idx = int(np.argmax(matrix))
        home_pred = int(idx // matrix.shape[1])
        away_pred = int(idx % matrix.shape[1])
        outcome = "H" if home_pred > away_pred else "D" if home_pred == away_pred else "A"
        exp_outcome = expected_goal_outcome(lam_raw, nu_raw, draw_threshold)

        row = {
            "league_id": league_id,
            "home_team": home_team,
            "away_team": away_team,
            "draw_threshold": round(float(draw_threshold), 3),
            "exp_home_goals": lam,
            "exp_away_goals": nu,
            "exp_outcome": exp_outcome,
            "pred_home_goals": home_pred,
            "pred_away_goals": away_pred,
            "pred_outcome": outcome,
            "p_home": ph,
            "p_draw": pd_raw,
            "p_away": pa,
            "fair_odds_home": round((1.0 / probs["H"]) if probs["H"] > 0 else np.nan, 3),
            "fair_odds_draw": round((1.0 / probs["D"]) if probs["D"] > 0 else np.nan, 3),
            "fair_odds_away": round((1.0 / probs["A"]) if probs["A"] > 0 else np.nan, 3),
            "note": "",
        }

        if top_k_scores and top_k_scores > 0:
            P = model.score_matrix(home_team, away_team)
            flat = P.ravel()
            k = int(top_k_scores)
            k = max(1, min(k, flat.size))
            top_idx = np.argpartition(-flat, k - 1)[:k]
            top_idx = top_idx[np.argsort(-flat[top_idx])]

            scores = []
            for idx in top_idx:
                x = int(idx // P.shape[1])
                y = int(idx % P.shape[1])
                scores.append({"score": f"{x}-{y}", "p": float(flat[idx])})

            row["most_likely_score"] = scores[0]["score"]
            row["p_most_likely_score"] = scores[0]["p"]
            row["top_scorelines"] = json.dumps(scores, ensure_ascii=False)
        return row
    except KeyError:
        if on_unknown_team == "error":
            raise
        return {
            "league_id": league_id,
            "home_team": home_team,
            "away_team": away_team,
            "draw_threshold": round(float(draw_threshold), 3),
            "exp_home_goals": np.nan,
            "exp_away_goals": np.nan,
            "exp_outcome": np.nan,
            "p_home": np.nan,
            "p_draw": np.nan,
            "p_away": np.nan,
            "fair_odds_home": np.nan,
            "fair_odds_draw": np.nan,
            "fair_odds_away": np.nan,
            "note": "unknown_team",
        }


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate predictions from a Dixon–Coles model artifact."
                                     " Output includes expected goals, most likely score/outcome, and probabilities.")
    p.add_argument("--artifact", type=str, default=None, help="Path to a single <league_id>.joblib artifact")
    p.add_argument("--artifacts-dir", type=str, default=None, help="Directory of league artifacts for mixed-league batch prediction")
    p.add_argument("--fixtures", type=str, required=True, help="CSV/XLSX containing fixtures")
    p.add_argument("--league-col", type=str, default=None, help="League/division column in fixtures (required with --artifacts-dir)")
    p.add_argument("--home-col", type=str, default="HomeTeam", help="Column name for home team")
    p.add_argument("--away-col", type=str, default="AwayTeam", help="Column name for away team")
    p.add_argument("--out", type=str, default=None, help="Output CSV path (optional) – includes predicted outcome; market odds are not required.")
    p.add_argument(
        "--top-k-scores",
        type=int,
        default=0,
        help="If >0, also output top-k most likely exact scorelines (JSON string column).",
    )
    p.add_argument(
        "--on-unknown-team",
        type=str,
        default="nan",
        choices=["nan", "error"],
        help="What to do if a team isn't in the model: 'nan' or 'error'",
    )
    p.add_argument(
        "--draw-threshold",
        type=float,
        default=0.25,
        help="If abs(exp_home_goals - exp_away_goals) is at or below this cutoff, set exp_outcome to 'D'.",
    )
    p.add_argument(
        "--threshold-map",
        type=str,
        default=None,
        help="Optional JSON mapping of league_id to draw_threshold, e.g. backtests_threshold_sweep/best_exp_thresholds_all.json",
    )
    return p.parse_args()


def read_table(path: Path) -> pd.DataFrame:
    if path.suffix.lower() in [".xlsx", ".xls"]:
        return pd.read_excel(path)
    return pd.read_csv(path)


def main() -> None:
    args = parse_args()

    if not args.artifact and not args.artifacts_dir:
        raise SystemExit("Provide either --artifact or --artifacts-dir")
    if args.artifact and args.artifacts_dir:
        raise SystemExit("Use either --artifact or --artifacts-dir, not both")
    if args.artifacts_dir and not args.league_col:
        raise SystemExit("--league-col is required when using --artifacts-dir")

    threshold_map = load_threshold_map(args.threshold_map)

    fixtures_path = Path(args.fixtures)
    fx = read_table(fixtures_path)

    if args.home_col not in fx.columns or args.away_col not in fx.columns:
        raise SystemExit(f"Missing columns. Need {args.home_col!r} and {args.away_col!r}")
    if args.league_col and args.league_col not in fx.columns:
        raise SystemExit(f"Missing league column: {args.league_col!r}")

    out_rows = []

    if args.artifact:
        artifact, model = load_artifact_model(Path(args.artifact))
        league_id = str(artifact.get("league_id", "unknown"))
        draw_threshold = resolve_draw_threshold(league_id, args.draw_threshold, threshold_map)
        for h, a in zip(fx[args.home_col].astype(str).str.strip(), fx[args.away_col].astype(str).str.strip()):
            out_rows.append(
                predict_row(
                    model=model,
                    league_id=league_id,
                    home_team=h,
                    away_team=a,
                    top_k_scores=args.top_k_scores,
                    on_unknown_team=args.on_unknown_team,
                    draw_threshold=draw_threshold,
                )
            )
    else:
        artifacts_dir = Path(args.artifacts_dir)
        model_cache: Dict[str, Tuple[dict, object]] = {}
        leagues = fx[args.league_col].astype(str).str.strip()
        homes = fx[args.home_col].astype(str).str.strip()
        aways = fx[args.away_col].astype(str).str.strip()

        for league_id, h, a in zip(leagues, homes, aways):
            try:
                if league_id not in model_cache:
                    artifact_path = artifacts_dir / f"{league_id}.joblib"
                    if not artifact_path.exists():
                        raise FileNotFoundError(f"Artifact not found for league_id={league_id!r}: {artifact_path}")
                    model_cache[league_id] = load_artifact_model(artifact_path)
                artifact, model = model_cache[league_id]
                artifact_league_id = str(artifact.get("league_id", league_id))
                draw_threshold = resolve_draw_threshold(artifact_league_id, args.draw_threshold, threshold_map)
                out_rows.append(
                    predict_row(
                        model=model,
                        league_id=artifact_league_id,
                        home_team=h,
                        away_team=a,
                        top_k_scores=args.top_k_scores,
                        on_unknown_team=args.on_unknown_team,
                        draw_threshold=draw_threshold,
                    )
                )
            except FileNotFoundError:
                if args.on_unknown_team == "error":
                    raise
                out_rows.append(
                    {
                        "league_id": league_id,
                        "home_team": h,
                        "away_team": a,
                        "draw_threshold": np.nan,
                        "exp_home_goals": np.nan,
                        "exp_away_goals": np.nan,
                        "exp_outcome": np.nan,
                        "p_home": np.nan,
                        "p_draw": np.nan,
                        "p_away": np.nan,
                        "fair_odds_home": np.nan,
                        "fair_odds_draw": np.nan,
                        "fair_odds_away": np.nan,
                        "note": "artifact_missing",
                    }
                )

    pred = pd.DataFrame(out_rows)

    if args.out:
        Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        pred.to_csv(args.out, index=False)
    else:
        # Print top rows
        print(pred.head(20).to_string(index=False))


if __name__ == "__main__":
    main()
