#!/usr/bin/env python
"""Train one Dixon–Coles model per league and save artifacts.

This script:
  1) ingests data from:
     - a directory of `all-euro-data-<season>.xlsx` workbooks (each sheet = league)
     - optional `new_leagues_data.xlsx` workbook (each sheet = league_id)
  2) standardizes into a single master dataset
  3) keeps only the last N seasons per league
  4) trains one model per league
  5) saves artifacts to <out_dir>/<league_id>.joblib

Example:
  python train_models.py `
    --all-euro-dir data/euro `
    --new-leagues-file data/new_leagues_data.xlsx `
    --out-dir models `
    --processed-out processed/master_matches.parquet `
    --report-out processed/train_report.json `
    --last-n-seasons 3 `
    --half-life-days 180 `
    --max-goals 10 `
    --l2 0.001

Author: generated by ChatGPT
"""

from __future__ import annotations

import argparse
import json
from math import log
from pathlib import Path
from typing import List, Optional

import joblib
import pandas as pd

from src.ingest import build_master_dataset
from src.dixon_coles import DixonColesModel, artifact_from_model


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Train Dixon–Coles models per league")

    p.add_argument(
        "--all-euro-dir",
        type=str,
        default=None,
        help="Directory containing all-euro-data-*.xlsx files (optional)",
    )
    p.add_argument(
        "--all-euro-files",
        type=str,
        nargs="*",
        default=None,
        help="Explicit list of all-euro-data workbooks (optional; overrides --all-euro-dir)",
    )
    p.add_argument(
        "--new-leagues-file",
        type=str,
        default=None,
        help="Path to new_leagues_data.xlsx (optional)",
    )

    p.add_argument("--out-dir", type=str, required=True, help="Directory to write *.joblib artifacts")
    p.add_argument(
        "--processed-out",
        type=str,
        default=None,
        help="Optional path to save the unified dataset (csv or parquet)",
    )
    p.add_argument(
        "--report-out",
        type=str,
        default=None,
        help="Optional path to save training report JSON",
    )

    p.add_argument("--last-n-seasons", type=int, default=3, help="Keep last N seasons per league")
    p.add_argument(
        "--half-life-days",
        type=float,
        default=0.0,
        help="Exponential time-decay half-life in days. 0 disables time-decay.",
    )
    p.add_argument("--max-goals", type=int, default=10, help="Score grid truncation for predictions")
    p.add_argument("--l2", type=float, default=0.0, help="Ridge penalty strength")
    p.add_argument(
        "--xg-weight",
        type=float,
        default=0.0,
        help=(
            "Optional convex weight in [0,1] for adding an xG quasi-likelihood term. "
            "Requires columns home_xg/away_xg in the unified dataset. 0 disables."
        ),
    )
    p.add_argument(
        "--min-matches",
        type=int,
        default=80,
        help="Skip leagues with fewer played matches than this",
    )

    return p.parse_args()


def _discover_all_euro_files(all_euro_dir: Optional[str]) -> List[Path]:
    if not all_euro_dir:
        return []
    d = Path(all_euro_dir)
    if not d.exists():
        raise FileNotFoundError(f"all-euro-dir not found: {d}")

    # Prefer files matching the expected naming convention; fall back to all xlsx.
    files = sorted(d.glob("all-euro-data-*.xlsx"))
    if not files:
        files = sorted(d.glob("*.xlsx"))
    return list(files)


def _save_dataframe(df: pd.DataFrame, out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    suf = out_path.suffix.lower()

    if suf in [".parquet", ".pq"]:
        try:
            # coerce object columns to string to avoid mixed-type errors
            df_to_write = df.copy()
            for c in df_to_write.select_dtypes(include=["object"]).columns:
                df_to_write[c] = df_to_write[c].astype(str)
            df_to_write.to_parquet(out_path, index=False)
        except Exception as e:
            # Parquet writer might be missing; fall back to CSV
            fallback = out_path.with_suffix(".csv")
            df.to_csv(fallback, index=False)
            print(
                f"[warn] Failed to write parquet ({e}). Wrote CSV instead: {fallback}"
            )
    elif suf in [".csv"]:
        df.to_csv(out_path, index=False)
    else:
        # default to csv
        fallback = out_path.with_suffix(".csv")
        df.to_csv(fallback, index=False)
        print(f"[warn] Unknown extension {suf!r}. Wrote CSV instead: {fallback}")


def main() -> None:
    args = parse_args()

    # Resolve inputs
    if args.all_euro_files:
        all_euro_paths = [Path(p) for p in args.all_euro_files]
    else:
        all_euro_paths = _discover_all_euro_files(args.all_euro_dir)

    new_leagues_path = Path(args.new_leagues_file) if args.new_leagues_file else None

    if not all_euro_paths and new_leagues_path is None:
        raise SystemExit("No inputs provided. Use --all-euro-dir/--all-euro-files and/or --new-leagues-file")

    # Ingest
    master = build_master_dataset(
        all_euro_paths=all_euro_paths,
        new_leagues_path=new_leagues_path,
        last_n_seasons=args.last_n_seasons,
    )

    if master.empty:
        raise SystemExit("Master dataset is empty after ingestion.")

    if args.processed_out:
        _save_dataframe(master, Path(args.processed_out))

    # Time decay
    if args.half_life_days and args.half_life_days > 0:
        xi = log(2.0) / float(args.half_life_days)
    else:
        xi = 0.0

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    report = {
        "config": {
            "last_n_seasons": args.last_n_seasons,
            "half_life_days": args.half_life_days,
            "xi": xi,
            "max_goals": args.max_goals,
            "l2": args.l2,
            "xg_weight": args.xg_weight,
            "min_matches": args.min_matches,
        },
        "leagues": {},
    }

    # Train per league
    for league_id, g in master.groupby("league_id"):
        # played matches only
        train = g.dropna(subset=["home_goals", "away_goals"]).copy()

        if len(train) < args.min_matches:
            report["leagues"][league_id] = {
                "skipped": True,
                "reason": f"not enough matches ({len(train)} < {args.min_matches})",
            }
            continue

        model = DixonColesModel(
            xi=xi,
            max_goals=args.max_goals,
            l2=args.l2,
            xg_weight=float(args.xg_weight),
        )

        try:
            fit_res = model.fit(train)
            artifact = artifact_from_model(league_id=league_id, model=model)
            artifact_path = out_dir / f"{league_id}.joblib"
            joblib.dump(artifact, artifact_path)

            report["leagues"][league_id] = {
                "skipped": False,
                "artifact": str(artifact_path),
                **artifact.get("train_summary", {}),
            }

            print(
                f"[ok] {league_id}: matches={fit_res.n_matches}, teams={fit_res.n_teams}, "
                f"home_adv={fit_res.home_adv:.4f}, rho={fit_res.rho:.4f}, nll={fit_res.neg_loglik:.2f}"
            )

        except Exception as e:
            report["leagues"][league_id] = {
                "skipped": False,
                "error": str(e),
            }
            print(f"[error] {league_id}: {e}")

    if args.report_out:
        report_path = Path(args.report_out)
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")


if __name__ == "__main__":
    main()
