"""Dixon–Coles model implementation (MLE) with optional exponential time decay.

This module is designed to be used in a league-by-league training pipeline.
It returns a *serializable* artifact (plain dict) you can save with joblib.

Canonical training columns expected:
    - league_id (str)
    - season (str)
    - datetime (datetime64[ns])
    - home_team (str)
    - away_team (str)
    - home_goals (int)
    - away_goals (int)

Optional xG columns (for "xG-enhanced" fitting):
    - home_xg (float)
    - away_xg (float)

Optional columns:
    - odds_home / odds_draw / odds_away (float)

Author: generated by ChatGPT
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from scipy.optimize import minimize
from scipy.special import gammaln


@dataclass
class DCFitResult:
    teams: List[str]
    attack: np.ndarray
    defense: np.ndarray
    home_adv: float
    rho: float
    success: bool
    message: str
    n_matches: int
    n_teams: int
    date_min: Optional[pd.Timestamp]
    date_max: Optional[pd.Timestamp]
    neg_loglik: float


class DixonColesModel:
    """Fit/predict using the Dixon–Coles (1997) adjustment to the independent Poisson model."""

    def __init__(self, xi: float = 0.0, max_goals: int = 10, l2: float = 0.0, xg_weight: float = 0.0):
        """Create a model.

        Args:
            xi: time-decay rate (per day). Set 0.0 to disable decay.
            max_goals: scoreline grid truncation for predictions.
            l2: ridge penalty strength for stabilization.
            xg_weight: convex weight in [0,1] for adding an xG quasi-likelihood term.
                0.0 disables xG. If enabled, the optimizer minimizes:
                    (1-xg_weight)*NLL_goals + xg_weight*NLL_xg
                where NLL_xg uses the same Poisson intensity model but treats xG as
                a non-integer "count" (quasi-likelihood).
        """
        self.xi = float(xi)
        self.max_goals = int(max_goals)
        self.l2 = float(l2)
        self.xg_weight = float(xg_weight)

        self.fit_result: Optional[DCFitResult] = None
        self.team_to_idx: Optional[Dict[str, int]] = None

    # --- math helpers ---
    @staticmethod
    def _poisson_logpmf(k: np.ndarray, mu: np.ndarray) -> np.ndarray:
        # Works for non-negative integer k; also used as a quasi-likelihood for floats.
        return k * np.log(mu) - mu - gammaln(k + 1.0)

    @staticmethod
    def _tau(x: np.ndarray, y: np.ndarray, lam: np.ndarray, nu: np.ndarray, rho: float) -> np.ndarray:
        """Dixon–Coles low-score adjustment factor tau(x,y)."""
        tau = np.ones_like(lam, dtype=float)
        is_00 = (x == 0) & (y == 0)
        is_01 = (x == 0) & (y == 1)
        is_10 = (x == 1) & (y == 0)
        is_11 = (x == 1) & (y == 1)

        tau[is_00] = 1.0 - rho * lam[is_00] * nu[is_00]
        tau[is_01] = 1.0 + rho * lam[is_01]
        tau[is_10] = 1.0 + rho * nu[is_10]
        tau[is_11] = 1.0 - rho
        return tau

    @staticmethod
    def _unpack_params(p: np.ndarray, n_teams: int) -> Tuple[np.ndarray, np.ndarray, float, float]:
        """Parameter vector -> (attack, defense, home_adv, rho).

        Uses sum-to-zero constraints by setting the final team's parameters
        to the negative sum of the others.
        """
        a_free = p[: n_teams - 1]
        d_free = p[n_teams - 1 : 2 * (n_teams - 1)]
        home_adv = float(p[-2])
        rho = float(p[-1])

        attack = np.zeros(n_teams)
        defense = np.zeros(n_teams)
        attack[:-1] = a_free
        defense[:-1] = d_free
        attack[-1] = -attack[:-1].sum()
        defense[-1] = -defense[:-1].sum()

        return attack, defense, home_adv, rho

    # --- fitting ---
    def fit(
        self,
        df: pd.DataFrame,
        home_team_col: str = "home_team",
        away_team_col: str = "away_team",
        home_goals_col: str = "home_goals",
        away_goals_col: str = "away_goals",
        home_xg_col: str = "home_xg",
        away_xg_col: str = "away_xg",
        datetime_col: str = "datetime",
    ) -> DCFitResult:
        """Fit the model to a dataframe of matches."""

        data = df.copy()

        # Keep only rows with goals present
        data = data.dropna(subset=[home_team_col, away_team_col, home_goals_col, away_goals_col]).copy()
        data[home_goals_col] = data[home_goals_col].astype(int)
        data[away_goals_col] = data[away_goals_col].astype(int)

        if len(data) == 0:
            raise ValueError("No training rows after dropping missing goals.")

        teams = sorted(set(data[home_team_col]).union(set(data[away_team_col])))
        n = len(teams)
        self.team_to_idx = {t: i for i, t in enumerate(teams)}

        home_idx = data[home_team_col].map(self.team_to_idx).to_numpy()
        away_idx = data[away_team_col].map(self.team_to_idx).to_numpy()
        hg = data[home_goals_col].to_numpy()
        ag = data[away_goals_col].to_numpy()

        # Optional xG arrays (quasi-likelihood) — only used if enabled and present.
        use_xg = (
            self.xg_weight > 0
            and home_xg_col in data.columns
            and away_xg_col in data.columns
        )
        if use_xg:
            hxg = pd.to_numeric(data[home_xg_col], errors="coerce").to_numpy(dtype=float)
            axg = pd.to_numeric(data[away_xg_col], errors="coerce").to_numpy(dtype=float)
            xg_mask = np.isfinite(hxg) & np.isfinite(axg) & (hxg >= 0) & (axg >= 0)
            if not np.any(xg_mask):
                use_xg = False
        else:
            hxg = None
            axg = None
            xg_mask = None

        # Time-decay weights
        if self.xi > 0:
            if datetime_col not in data.columns:
                raise ValueError("xi>0 but datetime_col not found in dataframe")
            if data[datetime_col].isna().all():
                raise ValueError("xi>0 but all datetimes are NaT")
            latest = pd.to_datetime(data[datetime_col]).max()
            days_ago = (latest - pd.to_datetime(data[datetime_col])).dt.total_seconds().to_numpy() / 86400.0
            w = np.exp(-self.xi * days_ago)
            w = np.where(np.isfinite(w), w, 1.0)
        else:
            w = np.ones(len(data), dtype=float)

        W = float(np.sum(w))
        if W <= 0:
            raise ValueError("Non-positive total weight; check datetime parsing and xi")

        if use_xg:
            assert xg_mask is not None
            Wxg = float(np.sum(w * xg_mask.astype(float)))
            if Wxg <= 0:
                use_xg = False
        else:
            Wxg = 0.0

        def neg_weighted_loglik(p: np.ndarray) -> float:
            attack, defense, home_adv, rho = self._unpack_params(p, n)

            lam = np.exp(home_adv + attack[home_idx] - defense[away_idx])
            nu = np.exp(attack[away_idx] - defense[home_idx])

            tau = self._tau(hg, ag, lam, nu, rho)
            if np.any(tau <= 0):
                return 1e9

            ll = (
                np.log(tau)
                + self._poisson_logpmf(hg, lam)
                + self._poisson_logpmf(ag, nu)
            )
            # Base (goals) negative log-likelihood equals the original DC objective
            nll_goals = -float(np.sum(w * ll))  # = W * mean_nll_goals

            # Optional xG quasi-likelihood (no tau; xG isn't discrete low scores)
            if use_xg:
                assert hxg is not None and axg is not None and xg_mask is not None and Wxg > 0
                ll_xg = self._poisson_logpmf(hxg, lam) + self._poisson_logpmf(axg, nu)
                nll_xg = -float(np.sum(w * xg_mask.astype(float) * ll_xg))  # = Wxg * mean_nll_xg

                eta = float(np.clip(self.xg_weight, 0.0, 1.0))
                # Blend on a *per-weight* basis, then scale back to the original objective magnitude.
                mean_goals = nll_goals / W
                mean_xg = nll_xg / Wxg
                nll = W * ((1.0 - eta) * mean_goals + eta * mean_xg)
            else:
                nll = nll_goals

            if self.l2 > 0:
                nll += self.l2 * (np.sum(attack**2) + np.sum(defense**2))

            return float(nll)

        # init params
        p0 = np.zeros(2 * (n - 1) + 2, dtype=float)
        p0[-1] = -0.05  # rho initial

        bounds = [(None, None)] * len(p0)
        bounds[-1] = (-1.0, 1.0)  # rho bounds

        opt = minimize(neg_weighted_loglik, p0, method="L-BFGS-B", bounds=bounds)

        attack, defense, home_adv, rho = self._unpack_params(opt.x, n)

        date_min = None
        date_max = None
        if datetime_col in data.columns:
            dt = pd.to_datetime(data[datetime_col], errors="coerce")
            if not dt.isna().all():
                date_min = dt.min()
                date_max = dt.max()

        self.fit_result = DCFitResult(
            teams=teams,
            attack=attack,
            defense=defense,
            home_adv=float(home_adv),
            rho=float(rho),
            success=bool(opt.success),
            message=str(opt.message),
            n_matches=int(len(data)),
            n_teams=int(n),
            date_min=date_min,
            date_max=date_max,
            neg_loglik=float(opt.fun),
        )
        return self.fit_result

    # --- prediction ---
    def _require_fit(self) -> None:
        if self.fit_result is None or self.team_to_idx is None:
            raise RuntimeError("Model not fitted. Call fit() first.")

    def expected_goals(self, home_team: str, away_team: str) -> Tuple[float, float]:
        self._require_fit()
        if home_team not in self.team_to_idx:
            raise KeyError(f"Unknown home_team: {home_team!r}")
        if away_team not in self.team_to_idx:
            raise KeyError(f"Unknown away_team: {away_team!r}")

        i = self.team_to_idx[home_team]
        j = self.team_to_idx[away_team]
        lam = np.exp(self.fit_result.home_adv + self.fit_result.attack[i] - self.fit_result.defense[j])
        nu = np.exp(self.fit_result.attack[j] - self.fit_result.defense[i])
        return float(lam), float(nu)

    def score_matrix(self, home_team: str, away_team: str) -> np.ndarray:
        """Return scoreline matrix P[x,y] for x,y=0..max_goals (renormalized on grid)."""
        lam, nu = self.expected_goals(home_team, away_team)
        rho = self.fit_result.rho

        x = np.arange(self.max_goals + 1)
        y = np.arange(self.max_goals + 1)

        px = np.exp(self._poisson_logpmf(x, lam))
        py = np.exp(self._poisson_logpmf(y, nu))
        P = np.outer(px, py)

        # DC adjust only 0-0,0-1,1-0,1-1
        P[0, 0] *= (1.0 - rho * lam * nu)
        P[0, 1] *= (1.0 + rho * lam)
        P[1, 0] *= (1.0 + rho * nu)
        P[1, 1] *= (1.0 - rho)

        s = float(P.sum())
        if s > 0:
            P = P / s
        return P

    def outcome_probs(self, home_team: str, away_team: str) -> Dict[str, float]:
        """Return probabilities for Home/Draw/Away."""
        P = self.score_matrix(home_team, away_team)
        p_home = float(np.tril(P, -1).sum())  # x>y
        p_draw = float(np.trace(P))
        p_away = float(np.triu(P, 1).sum())   # x<y
        return {"H": p_home, "D": p_draw, "A": p_away}


def artifact_from_model(league_id: str, model: DixonColesModel) -> Dict:
    """Build a serializable artifact dict from a fitted model."""
    model._require_fit()
    fr = model.fit_result
    assert fr is not None

    return {
        "artifact_version": 1,
        "league_id": league_id,
        "trained_at_utc": datetime.now(timezone.utc).isoformat(),
        "config": {
            "xi": model.xi,
            "max_goals": model.max_goals,
            "l2": model.l2,
            "xg_weight": model.xg_weight,
        },
        "params": {
            "teams": fr.teams,
            "team_to_idx": model.team_to_idx,
            "attack": fr.attack.tolist(),
            "defense": fr.defense.tolist(),
            "home_adv": fr.home_adv,
            "rho": fr.rho,
        },
        "train_summary": {
            "n_matches": fr.n_matches,
            "n_teams": fr.n_teams,
            "date_min": None if fr.date_min is None else str(fr.date_min),
            "date_max": None if fr.date_max is None else str(fr.date_max),
            "neg_loglik": fr.neg_loglik,
            "success": fr.success,
            "message": fr.message,
        },
    }


def model_from_artifact(artifact: Dict) -> DixonColesModel:
    """Recreate a DixonColesModel instance from an artifact dict."""
    cfg = artifact.get("config", {})
    params = artifact.get("params", {})

    model = DixonColesModel(
        xi=float(cfg.get("xi", 0.0)),
        max_goals=int(cfg.get("max_goals", 10)),
        l2=float(cfg.get("l2", 0.0)),
        xg_weight=float(cfg.get("xg_weight", 0.0)),
    )

    teams = params["teams"]
    attack = np.array(params["attack"], dtype=float)
    defense = np.array(params["defense"], dtype=float)
    home_adv = float(params["home_adv"])
    rho = float(params["rho"])

    model.team_to_idx = {t: int(i) for t, i in params["team_to_idx"].items()}

    fr = DCFitResult(
        teams=list(teams),
        attack=attack,
        defense=defense,
        home_adv=home_adv,
        rho=rho,
        success=True,
        message="loaded from artifact",
        n_matches=int(artifact.get("train_summary", {}).get("n_matches", 0)),
        n_teams=len(teams),
        date_min=None,
        date_max=None,
        neg_loglik=float(artifact.get("train_summary", {}).get("neg_loglik", np.nan)),
    )
    model.fit_result = fr
    return model
