"""Data ingestion utilities for multiple Excel workbooks.

Supports two sources:
  1) all-euro-data-<season>.xlsx (each sheet = league code, e.g. E0)
  2) new_leagues_data.xlsx (each sheet = country abbreviation, 1 league per sheet)

Outputs a canonical matches dataframe with columns:
  - source (str)
  - league_id (str)
  - league_name (optional str)
  - country (optional str)
  - season (str)
  - date (datetime64[ns])
  - time (string or time)
  - datetime (datetime64[ns])
  - home_team (str)
  - away_team (str)
  - home_goals (float/int)
  - away_goals (float/int)
  - home_xg (float)  [optional]
  - away_xg (float)  [optional]
  - result (str)
  - odds_home (float)
  - odds_draw (float)
  - odds_away (float)

Author: generated by ChatGPT
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Iterable, List, Optional, Tuple

import numpy as np
import pandas as pd


# Common column name variants for expected-goals (xG)
_XG_HOME_CANDIDATES = [
    "HxG",
    "H_xG",
    "Home_xG",
    "HomeXG",
    "xGHome",
    "xGH",
    "home_xg",
    "homeXG",
]
_XG_AWAY_CANDIDATES = [
    "AxG",
    "A_xG",
    "Away_xG",
    "AwayXG",
    "xGAway",
    "xGA",
    "away_xg",
    "awayXG",
]


def _rename_first_present(df: pd.DataFrame, candidates: List[str], new_name: str) -> pd.DataFrame:
    """If any candidate column exists, rename the first match to new_name."""
    for c in candidates:
        if c in df.columns:
            return df.rename(columns={c: new_name})
    return df


def _extract_season_from_filename(path: Path) -> Optional[str]:
    """Try to infer season string from filename.

    Supports:
      - all-euro-data-2025-2026.xlsx
      - all-euro-data-2025_2026.xlsx
      - all-euro-data-2025-26.xlsx  (will normalize to 2025/2026 if possible)

    Returns None if not found.
    """
    name = path.stem

    # Prefer 4-digit/4-digit
    m = re.search(r"(\d{4})[-_](\d{4})", name)
    if m:
        y1, y2 = m.group(1), m.group(2)
        return f"{y1}/{y2}"

    # 4-digit / 2-digit
    m = re.search(r"(\d{4})[-_](\d{2})", name)
    if m:
        y1, y2s = int(m.group(1)), int(m.group(2))
        # Heuristic: 2025-26 -> 2025/2026
        y2 = (y1 // 100) * 100 + y2s
        if y2 < y1:
            y2 += 100
        return f"{y1}/{y2}"

    return None


def _season_start_year(season: str) -> Optional[int]:
    """Extract the start year from a season string.

    Examples:
      - '2025/2026' -> 2025
      - '2025-2026' -> 2025
      - '2025'      -> 2025
    """
    if season is None or (isinstance(season, float) and np.isnan(season)):
        return None
    s = str(season)
    m = re.search(r"(\d{4})", s)
    return int(m.group(1)) if m else None


def keep_last_n_seasons(df: pd.DataFrame, season_col: str, n: int = 3) -> pd.DataFrame:
    """Keep only rows belonging to the last n seasons (by start year), per league."""
    if season_col not in df.columns:
        return df

    out = []
    for league_id, g in df.groupby("league_id", dropna=False):
        seasons = g[season_col].dropna().astype(str).unique().tolist()
        # Sort by extracted start year, fall back to string sort
        seasons_sorted = sorted(
            seasons,
            key=lambda s: (_season_start_year(s) if _season_start_year(s) is not None else -10**9, s),
        )
        keep = set(seasons_sorted[-n:])
        out.append(g[g[season_col].astype(str).isin(keep)])

    return pd.concat(out, ignore_index=True) if out else df.iloc[0:0].copy()


def load_all_euro_workbooks(paths: Iterable[Path]) -> pd.DataFrame:
    """Load and concatenate all sheets from all-euro-data workbooks."""
    frames: List[pd.DataFrame] = []

    for path in paths:
        path = Path(path)
        season = _extract_season_from_filename(path)

        xl = pd.ExcelFile(path)
        for sheet in xl.sheet_names:
            df = pd.read_excel(path, sheet_name=sheet)

            # Minimal columns (many more exist)
            cols = {
                "Div": "league_id",
                "Date": "date",
                "Time": "time",
                "HomeTeam": "home_team",
                "AwayTeam": "away_team",
                "FTHG": "home_goals",
                "FTAG": "away_goals",
                "FTR": "result",
                "B365H": "odds_home",
                "B365D": "odds_draw",
                "B365A": "odds_away",
            }

            keep = [c for c in cols.keys() if c in df.columns]
            # retain optional xG columns if present
            keep_xg = [c for c in (_XG_HOME_CANDIDATES + _XG_AWAY_CANDIDATES) if c in df.columns]
            keep = list(dict.fromkeys(keep + keep_xg))
            df = df[keep].rename(columns=cols)
            df = _rename_first_present(df, _XG_HOME_CANDIDATES, "home_xg")
            df = _rename_first_present(df, _XG_AWAY_CANDIDATES, "away_xg")

            # Some files have Div but it should match sheet; prefer Div if present, else use sheet
            if "league_id" not in df.columns or df["league_id"].isna().all():
                df["league_id"] = sheet

            df["league_id"] = df["league_id"].astype(str).str.strip()

            df["season"] = season if season is not None else "unknown"
            df["source"] = "all_euro"

            # datetime combine
            df["date"] = pd.to_datetime(df["date"], errors="coerce")
            if "time" in df.columns:
                # time can be datetime.time, string, or missing
                # Convert to string HH:MM:SS then parse
                t = df["time"].astype(str)
                # Handle 'nan'
                t = t.replace({"nan": "00:00:00", "NaT": "00:00:00"})
                df["datetime"] = pd.to_datetime(df["date"].dt.date.astype(str) + " " + t, errors="coerce")
            else:
                df["datetime"] = df["date"]

            # normalize team strings
            df["home_team"] = df["home_team"].astype(str).str.strip()
            df["away_team"] = df["away_team"].astype(str).str.strip()

            frames.append(df)

    out = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
    return out


def load_new_leagues_workbook(path: Path) -> pd.DataFrame:
    """Load and concatenate all sheets from new_leagues_data workbook."""
    frames: List[pd.DataFrame] = []

    path = Path(path)
    xl = pd.ExcelFile(path)

    for sheet in xl.sheet_names:
        df = pd.read_excel(path, sheet_name=sheet)

        cols = {
            "Country": "country",
            "League": "league_name",
            "Season": "season",
            "Date": "date",
            "Time": "time",
            "Home": "home_team",
            "Away": "away_team",
            "HG": "home_goals",
            "AG": "away_goals",
            "Res": "result",
            "B365CH": "odds_home",
            "B365CD": "odds_draw",
            "B365CA": "odds_away",
        }
        keep = [c for c in cols.keys() if c in df.columns]
        keep_xg = [c for c in (_XG_HOME_CANDIDATES + _XG_AWAY_CANDIDATES) if c in df.columns]
        keep = list(dict.fromkeys(keep + keep_xg))
        df = df[keep].rename(columns=cols)
        df = _rename_first_present(df, _XG_HOME_CANDIDATES, "home_xg")
        df = _rename_first_present(df, _XG_AWAY_CANDIDATES, "away_xg")

        df["league_id"] = sheet
        df["source"] = "new_leagues"

        df["league_id"] = df["league_id"].astype(str).str.strip()
        if "league_name" in df.columns:
            df["league_name"] = df["league_name"].astype(str).str.strip()
        if "country" in df.columns:
            df["country"] = df["country"].astype(str).str.strip()

        # datetime combine
        df["date"] = pd.to_datetime(df["date"], errors="coerce")
        if "time" in df.columns:
            t = df["time"].astype(str)
            t = t.replace({"nan": "00:00:00", "NaT": "00:00:00"})
            df["datetime"] = pd.to_datetime(df["date"].dt.date.astype(str) + " " + t, errors="coerce")
        else:
            df["datetime"] = df["date"]

        df["home_team"] = df["home_team"].astype(str).str.strip()
        df["away_team"] = df["away_team"].astype(str).str.strip()

        frames.append(df)

    out = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame()
    return out


def build_master_dataset(
    all_euro_paths: Iterable[Path],
    new_leagues_path: Optional[Path] = None,
    last_n_seasons: int = 3,
) -> pd.DataFrame:
    """Load all sources, standardize columns, keep last N seasons per league, and concatenate."""

    frames: List[pd.DataFrame] = []

    all_euro_paths = list(all_euro_paths)
    if all_euro_paths:
        frames.append(load_all_euro_workbooks(all_euro_paths))

    if new_leagues_path is not None:
        frames.append(load_new_leagues_workbook(new_leagues_path))

    if not frames:
        return pd.DataFrame()

    df = pd.concat(frames, ignore_index=True)

    # Canonical ordering / ensure columns exist
    for col in [
        "source",
        "league_id",
        "country",
        "league_name",
        "season",
        "date",
        "time",
        "datetime",
        "home_team",
        "away_team",
        "home_goals",
        "away_goals",
        "home_xg",
        "away_xg",
        "result",
        "odds_home",
        "odds_draw",
        "odds_away",
    ]:
        if col not in df.columns:
            df[col] = np.nan

    # Keep last N seasons per league
    if last_n_seasons is not None and last_n_seasons > 0:
        df = keep_last_n_seasons(df, "season", n=last_n_seasons)

    # Coerce goal/odds numeric
    df["home_goals"] = pd.to_numeric(df["home_goals"], errors="coerce")
    df["away_goals"] = pd.to_numeric(df["away_goals"], errors="coerce")
    df["home_xg"] = pd.to_numeric(df["home_xg"], errors="coerce")
    df["away_xg"] = pd.to_numeric(df["away_xg"], errors="coerce")
    df["odds_home"] = pd.to_numeric(df["odds_home"], errors="coerce")
    df["odds_draw"] = pd.to_numeric(df["odds_draw"], errors="coerce")
    df["odds_away"] = pd.to_numeric(df["odds_away"], errors="coerce")

    # Standardize result values (H/D/A)
    if "result" in df.columns:
        df["result"] = df["result"].astype(str).str.strip().str.upper()
        df.loc[~df["result"].isin(["H", "D", "A"]), "result"] = np.nan

    # Some safety cleanup
    df["home_team"] = df["home_team"].astype(str).str.strip()
    df["away_team"] = df["away_team"].astype(str).str.strip()

    # Remove obviously invalid matches
    df = df[(df["home_team"] != "") & (df["away_team"] != "")]
    df = df[df["home_team"].notna() & df["away_team"].notna()]

    # Sort
    df = df.sort_values(["league_id", "datetime"], na_position="last").reset_index(drop=True)

    return df
